#!/usr/local/bin/zsh
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0"})"; pwd)
. $SCRIPT_DIR/elastic-conf.sh

INDEX=zsh_history
# curl ${ELASTIC_CURL_OPT[@]} -XPUT $ELASTIC_CURL_URL/$INDEX -d '{
#   "mappings": {
#     "command": {
#       "properties": {
#         "date": { "type": "date", "format": "yyyy-MM-dd HH:mm Z" },
#         "command" : { "type": "string", "index": "not_analyzed" }
#       }
#     }
#   }
# }'

source ~/.zshrc >/dev/null 2>/dev/null
fc -R
fc -l -i -D 1 | \
  ruby $SCRIPT_DIR/zsh_history_to_json.rb | \
  curl -s ${ELASTIC_CURL_OPT[@]} -XPOST $ELASTIC_CURL_URL/_bulk --data-binary @- \
  >/dev/null
